In [2]:
import pandas as pd

In [3]:
df_usuario = pd.read_csv('usuarios.csv', delimiter=',', encoding='utf-8', index_col=None)
df_departamento = pd.read_csv('departamentos.csv', delimiter=',', encoding='utf-8', index_col=None)
df_chamado = pd.read_csv('chamados.csv',  delimiter=',', encoding='utf-8', index_col=None)

In [39]:
df_departamento

   Codigo Nome_Departamento                       Descrição
0     145            Vendas               Foco no em vendas
1     167                RH                Recursos humanos
2     567                TI        Tecnologia da Informação
3     324         Marketing       Departamento de Marketing
4     234     Contabilidade   Departamento de contabilidade
5     215          Produção        Departamento de produção
6     657          Pesquisa  Pesquisas para desenvolvimento

In [5]:
def usuario_por_departamento(df_usuario, df_departamento):
    # Mesclar os DataFrames de usuários e departamentos usando o campo 'Código_Departamento'
    df_completo = pd.merge(df_usuario, df_departamento, left_on='Código_Departamento', right_on='Codigo')
    # Ordenando o dataframe
    df_ordenado = df_completo.sort_values(['Nome', 'Nome_Departamento'])

    return df_ordenado

In [6]:
relacao = usuario_por_departamento(df_usuario, df_departamento)
relacao

,ID_Usuário,Nome,Código_Departamento,CPF,Email,Cargo,Codigo,Nome_Departamento,Descrição
4,10,Amanda Bonde,324,617.123.896-78,amanda@us.eosphoro.com,Designer de marketing,324,Marketing,Departamento de Marketing
5,4,Ana Souza,657,789.012.345-67,ana@us.eosphoro.com,Analista de Redes,657,Pesquisa,Pesquisas para desenvolvimento
3,3,Carlos Santos,324,456.789.012-34,carlos@us.eosphoro.com,Gerente de Projetos,324,Marketing,Departamento de Marketing
0,1,João Silva,567,123.456.789-01,joao@us.eosphoro.com,Analista de TI,567,TI,Tecnologia da Informação
6,6,Juliana Pereira,657,567.890.123-45,juliana@us.eosphoro.com,Analista de Sistemas,657,Pesquisa,Pesquisas para desenvolvimento
9,9,Kevin Richard,215,823.123.456-78,kevin@us.eosphoro.com,Engenheiro de Produção,215,Produção,Departamento de produção
8,8,Leandro Dionisio,215,190.123.457-78,leandro@us.eosphoro.com,Técnico de Manutenção,215,Produção,Departamento de produção
7,7,Luiz Costa,215,890.123.456-78,luiz@us.eosphoro.com,Analista de Segurança,215,Produção,Departamento de produção
2,2,Maria Oliveira,324,987.654.321-01,maria@us.eosphoro.com,Gerente de Marketing,324,Marketing,Departamento de Marketing
1,5,Pedro Lima,567,234.567.890-12,pedro@us.eosphoro.com,Suporte,567,TI,Tecnologia da Informação

In [10]:
def chamados_por_prioridade(df_chamados):
    # Mapeia os status para níveis de prioridade
    prioridade_map = {'Fechado': 0, 'Em Andamento': 1, 'Aberto': 2}

    # Adiciona uma coluna de prioridade com base no mapeamento
    df_chamados['Prioridade'] = df_chamados['Status'].map(prioridade_map)

    # Ordena o DataFrame por prioridade e data de abertura
    df_ordenado = df_chamados.sort_values(by=['Prioridade', 'Data de Abertura'])

    # Remove a coluna de prioridade que não é mais necessária
    df_ordenado = df_ordenado.drop('Prioridade', axis=1)

    return df_ordenado

In [12]:
relacao = chamados_por_prioridade(df_chamado)
relacao

,ID,Título,Descrição,Data de Abertura,Hora,Status,ID do Usuário Solicitante
3,4,Problema na Rede,Conexão instável,2023-10-04,11:20:00,Fechado,2
1,2,Erro no Software X,Falha ao iniciar,2023-10-02,14:30:00,Em Andamento,3
4,5,Ajuda com Senha,Esqueci minha senha,2023-10-05,16:00:00,Em Andamento,1
6,7,Problema de Hardware,Falha no hardware,2023-10-07,08:00:00,Em Andamento,7
0,1,Problema com Impressora,Não está imprimindo,2023-10-01,10:15:00,Aberto,7
2,3,Solicitação de Novo Software,Instalação do Software Y,2023-10-03,09:45:00,Aberto,5
5,6,Atualização de Sistema,Solicitação de atualização,2023-10-06,13:10:00,Aberto,6

In [29]:
def usuario_com_mais_chamados(df_chamados, df_usuarios):
    # Conta o número de chamados por ID de usuário
    contagem_chamados_por_usuario = df_chamados['ID do Usuário Solicitante'].value_counts()

    # Obtém o ID do usuário com o maior número de chamados
    id_usuario_mais_chamados = contagem_chamados_por_usuario.idxmax()

    # Obtém o nome do usuário correspondente
    nome_usuario_mais_chamados = df_usuarios.loc[df_usuarios['ID_Usuário'] == id_usuario_mais_chamados, 'Nome'].iloc[0]

    # Obtém a quantidade correspondente de chamados
    quantidade_chamados = contagem_chamados_por_usuario.max()

    return nome_usuario_mais_chamados, quantidade_chamados

In [30]:
usuario_com_mais_chamados, quantidade_chamados = usuario_com_mais_chamados(df_chamado, df_usuario)
print(f'Usuário com mais chamados: {usuario_com_mais_chamados} || Quantiade de chamados: {quantidade_chamados}')

Usuário com mais chamados: Luiz Costa || Quantiade de chamados: 2

In [42]:
def chamados_por_departamento(df_chamado, df_departamento, df_usuario):
    df_completo = pd.merge(df_chamado, df_usuario, left_on='ID do Usuário Solicitante', right_on='ID_Usuário')
    df_completo = pd.merge(df_completo, df_departamento, left_on='Código_Departamento', right_on='Codigo')

    # Agrupa os chamados pelo departamento e conta a quantidade
    quantidade_por_departamento = df_completo.groupby('Nome_Departamento')['ID'].count().reset_index()
    quantidade_por_departamento.columns = ['Nome_Departamento', 'Quantidade_de_Chamados']
    
    return quantidade_por_departamento

In [43]:
quantidade_por_departamento = chamados_por_departamento(df_chamado, df_departamento, df_usuario)
quantidade_por_departamento

  Nome_Departamento  Quantidade_de_Chamados
0         Marketing                       2
1          Pesquisa                       1
2          Produção                       2
3                TI                       2